---
title: "R_install_test"
subtitle: "`r date()`"
output:
  pdf_document: default
  html_document: default
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, output_dir = "~") })
---

## Purpose

The purpose of this markdown is to test a handful of packages and functions for proper execution in the environment. 

```{r}
system("uname -a", intern=TRUE)
```

```{r}
unique(rownames(installed.packages()))
```

## Load packages
Load some packages for testing.
```{r load packages}
library(boot)
library(Hmisc)
library(tidyverse)
library(clustMixType)
library(COUNT)
library(grf)
library(e1071)
```

## Testing boot
```{r}
# function to obtain R square
rsq <- function(formula, data, indices) {
  d <- data[indices, ]
  fit <- lm(formula, data = d)
  return(summary(fit)$r.square)
}

# bootstrapping with 1000 replications
results <- boot(data = mtcars, statistic = rsq, R = 1000, formula = mpg~wt + disp)

# view results
results

# get 95% confidence interval
boot.ci(results, type = "bca")

```

## Testing COUNT
```{r}
sim.data <- poisson_syn(nobs = 500, xv = c(2, .75, -1.25))
mypo <- glm(py ~ . , family=poisson, data = sim.data)
summary(mypo)
confint(mypo)
```

# Test grf

```{r}
# Generate data.
n <- 2000
p <- 10
X <- matrix(rnorm(n * p), n, p)
X.test <- matrix(0, 101, p)
X.test[, 1] <- seq(-2, 2, length.out = 101)

# Train a causal forest.
W <- rbinom(n, 1, 0.4 + 0.2 * (X[, 1] > 0))
Y <- pmax(X[, 1], 0) * W + X[, 2] + pmin(X[, 3], 0) + rnorm(n)
tau.forest <- causal_forest(X, Y, W)

# Estimate treatment effects for the training data using out-of-bag prediction.
tau.hat.oob <- predict(tau.forest)
hist(tau.hat.oob$predictions)

# Estimate treatment effects for the test sample.
tau.hat <- predict(tau.forest, X.test)
plot(X.test[, 1], tau.hat$predictions, ylim = range(tau.hat$predictions, 0, 2), xlab = "x", ylab = "tau", type = "l")
lines(X.test[, 1], pmax(0, X.test[, 1]), col = 2, lty = 2)

# Estimate the conditional average treatment effect on the full sample (CATE).
average_treatment_effect(tau.forest, target.sample = "all")

# Estimate the conditional average treatment effect on the treated sample (CATT).
average_treatment_effect(tau.forest, target.sample = "treated")

# Add confidence intervals for heterogeneous treatment effects; growing more trees is now recommended.
tau.forest <- causal_forest(X, Y, W, num.trees = 4000)
tau.hat <- predict(tau.forest, X.test, estimate.variance = TRUE)
sigma.hat <- sqrt(tau.hat$variance.estimates)
plot(X.test[, 1], tau.hat$predictions, ylim = range(tau.hat$predictions + 1.96 * sigma.hat, tau.hat$predictions - 1.96 * sigma.hat, 0, 2), xlab = "x", ylab = "tau", type = "l")
lines(X.test[, 1], tau.hat$predictions + 1.96 * sigma.hat, col = 1, lty = 2)
lines(X.test[, 1], tau.hat$predictions - 1.96 * sigma.hat, col = 1, lty = 2)
lines(X.test[, 1], pmax(0, X.test[, 1]), col = 2, lty = 1)

# In some examples, pre-fitting models for Y and W separately may
# be helpful (e.g., if different models use different covariates).
# In some applications, one may even want to get Y.hat and W.hat
# using a completely different method (e.g., boosting).

# Generate new data.
n <- 4000
p <- 20
X <- matrix(rnorm(n * p), n, p)
TAU <- 1 / (1 + exp(-X[, 3]))
W <- rbinom(n, 1, 1 / (1 + exp(-X[, 1] - X[, 2])))
Y <- pmax(X[, 2] + X[, 3], 0) + rowMeans(X[, 4:6]) / 2 + W * TAU + rnorm(n)

forest.W <- regression_forest(X, W, tune.parameters = "all")
W.hat <- predict(forest.W)$predictions

forest.Y <- regression_forest(X, Y, tune.parameters = "all")
Y.hat <- predict(forest.Y)$predictions

forest.Y.varimp <- variable_importance(forest.Y)

# Note: Forests may have a hard time when trained on very few variables
# (e.g., ncol(X) = 1, 2, or 3). We recommend not being too aggressive
# in selection.
selected.vars <- which(forest.Y.varimp / mean(forest.Y.varimp) > 0.2)

tau.forest <- causal_forest(X[, selected.vars], Y, W,
                            W.hat = W.hat, Y.hat = Y.hat,
                            tune.parameters = "all")

# Check whether causal forest predictions are well calibrated.
test_calibration(tau.forest)
```


## Testing e1071
```{r}
x <- iris[,-5]
y <- iris[5]
model_svm <- svm(Species ~., data=iris)
summary(model_svm)

pred <- predict(model_svm, x)
caret::confusionMatrix(pred, y$Species)

data(cats, package = "MASS")
m <- svm(Sex~., data = cats)
plot(m, cats)
```


## Testing Hmisc
```{r}
describe(iris)
```


## Testing tidyverse

```{r tidyverse}
iris_tibble <- 
  iris %>% 
  group_by(Species) %>% 
  mutate(across(everything(), mean, .names = "{col}_{fn}"))

iris_tibble

?ggplot2

ggplot(iris_tibble) +
  geom_point(aes(x=Sepal.Length, y=Sepal.Width))
```

## Test plot
```{r}
plot(pressure)
```


## Things that don't work
Note: All should be true with the exception of x11, aqua, and cledit. 

```{r}
cap <- capabilities()
cap[cap==TRUE]
cap[cap==FALSE]
```

## SessionInfo()

```{r}
sessionInfo()
```































