name: set-r-pkgs-repos

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
         r-version: '4.2.0'
         use-public-rspm: false
        
      - name: Install packages 
        run: |
          install.packages(c("httr"), repos = "https://packagemanager.rstudio.com/cran/2023-01-30")
        shell: Rscript {0}
      
      - name: Print Package version
        run: | 
          packageVersion('httr')
        shell: Rscript {0}
